os:
  - linux
  - windows

language: node_js

sudo: false

cache:
  apt: true
  directories:
    - node_modules

node_js:
  - "8"
  - "10"
  - "node"

script:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then
      npm run eslint;
    fi
  - npm run test-cov

after_script:
  - npm install coveralls
  - nyc report --reporter=text-lcov | coveralls
